const express = require('express');
const router = express.Router();
const enterpriseController = require('../controllers/enterpriseControllerApi');
const unplastifyController = require('../controllers/unplastifyControllerApi');
const { validationResult } = require('express-validator');
const userNotLoggedAsEnterprise = require('../middlewares/userNotLoggedAsEnterprise');
const userNotLoggedAsUnplastify = require('../middlewares/userNotLoggedAsUnplastify');
const userNotLogged = require('../middlewares/userNotLogged');
const editPermision = require('../middlewares/mintingRequestEdit');
const upload = require('../middlewares/mintingUpload');
const namingMintingRequest = require('../middlewares/namingMintingRequest');
// hay que hacer un midleware para que solo se pueda renderizar si la mintingRequest es del user_id

// router.get('/home', userNotLoggedAsEnterprise, enterpriseController.dashboard);
router.get('/home', enterpriseController.dashboard);
// router.get('/details', userNotLoggedAsEnterprise, enterpriseController.details);
router.get('/details', enterpriseController.details);
// router.put('/details', userNotLoggedAsEnterprise, enterpriseController.details);
router.put('/details', enterpriseController.details);
// router.post('/details/:id', userNotLoggedAsEnterprise, enterpriseController.processEnterpriseDetails);
router.post('/details/:id', enterpriseController.processEnterpriseDetails);
// router.post('/newMintingRequest', userNotLoggedAsEnterprise, namingMintingRequest, enterpriseController.newMintingRequest);
router.post('/newMintingRequest', namingMintingRequest, enterpriseController.newMintingRequest);
// router.get('/mintingRequest/:idMintingRequest', userNotLogged, enterpriseController.mintingRequestDetail);
router.get('/mintingRequest/:idMintingRequest', enterpriseController.mintingRequestDetail);
// router.get('/addUnplastifiedItem', userNotLoggedAsEnterprise, enterpriseController.addNewUnplastifiedItem);
router.get('/addUnplastifiedItem', enterpriseController.addNewUnplastifiedItem);
// router.post('/newUnplastifiedItem', userNotLoggedAsEnterprise, upload.any('before_pic','after_pic', 'video', 'technical_file', 'additional_pics'), enterpriseController.uploadUnplastifiedItem);
router.post('/newUnplastifiedItem', upload.any('before_pic','after_pic', 'video', 'technical_file', 'additional_pics'), enterpriseController.uploadUnplastifiedItem);
// router.put('/editUnplastifiedItem/:idUnplastifiedItem', userNotLogged, editPermision, upload.any('before_pic','after_pic', 'video', 'technical_file', 'additional_pics'), enterpriseController.editUnplastifiedItem);
router.put('/editUnplastifiedItem/:idUnplastifiedItem', upload.any('before_pic','after_pic', 'video', 'technical_file', 'additional_pics'), enterpriseController.editUnplastifiedItem);
// router.delete('/deleteUnplastifiedItem/:idUnplastifiedItem', userNotLoggedAsEnterprise, editPermision, editPermision, upload.any('additional_documents'), enterpriseController.deleteUnplastifiedItem);
router.delete('/deleteUnplastifiedItem/:idUnplastifiedItem', upload.any('additional_documents'), enterpriseController.deleteUnplastifiedItem);
// router.put('/changeMintingRequestName/:minting_request_id', userNotLoggedAsEnterprise, enterpriseController.changeMintingRequestName);
router.put('/changeMintingRequestName/:minting_request_id', enterpriseController.changeMintingRequestName);
// router.put('/submitMintingRequest/:minting_request_id', editPermision, enterpriseController.submitMintingRequest);
router.put('/submitMintingRequest/:minting_request_id', enterpriseController.submitMintingRequest);
// router.put('/assignToValidator/:minting_request_id', editPermision, userNotLoggedAsUnplastify, unplastifyController.assignMintingRequestToValidator);
// router.put('/inReview/:minting_request_id', editPermision, userNotLoggedAsUnplastify, enterpriseController.inReviewMintingRequest);
router.put('/inReview/:minting_request_id', enterpriseController.inReviewMintingRequest);
router.get('*', (req, res) => {
  res.redirect('/');
});
module.exports = router;
